FROM ibmcom/db2express-c:10.5.0.5-3.10.0

#RUN su - db2inst1 -c "db2start && db2 create db local"
#
#RUN /home/db2inst1/sqllib/bin/db2 -vtf /home/db2inst/path/<schemafilename>.sql

RUN /home/db2inst1/sqllib/bin/db2 create database DOCKER